In [5]:
import numpy as np

In [7]:
np.__version__

'1.24.4'

In [9]:
import sys 
sys.version

'3.8.11 (default, Jul 24 2021, 23:33:17) [MSC v.1929 64 bit (AMD64)]'

In [11]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [13]:
type(my_list)

list

In [15]:
arr = np.array(my_list) 

In [17]:
arr

array([0, 1, 2, 3, 4, 5])

In [19]:
type(arr)

numpy.ndarray

In [21]:
type(my_list)

list

In [23]:
np.arange(15) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
np.arange(3.0)  

array([0., 1., 2.])

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [31]:
np.arange(10,20) 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [33]:
np.arange(20,10)

array([], dtype=int32)

In [35]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [37]:
np.arange(-16,10) 

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [39]:
np.arange(-20,-10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [41]:
np.arange(30,20)

array([], dtype=int32)

In [43]:
np.zeros(3)

array([0., 0., 0.])

In [45]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [47]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [49]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [51]:
zero = np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [53]:
range(5)

range(0, 5)

In [55]:
r = range(5)
r

range(0, 5)

In [57]:
for i in r:
    print(i)

0
1
2
3
4


In [59]:
list(range(1,10,3))

[1, 4, 7]

In [61]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [63]:
np.random.randint(10,20,(4,4))

array([[17, 18, 16, 19],
       [12, 18, 11, 11],
       [19, 17, 12, 19],
       [14, 11, 17, 17]])

In [67]:
a = np.random.randint(10,20,10)
a

array([17, 18, 14, 14, 19, 19, 12, 14, 10, 11])

In [69]:
id(a)

1617921331920

In [71]:
arr2 = np.random.randint(0,100,(10,10))

In [73]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

3.0

In [75]:
arr.reshape(3,2)  

array([[0, 1],
       [2, 3],
       [4, 5]])

In [77]:
arr.reshape(2,3,order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [81]:
mat = np.arange(0,100).reshape(10,10) 

In [85]:
## To Generate OTP

import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 5104


In [87]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [91]:
# Create an array from a list
a = np.array([1, 2, 3])
print("Array a:", a)

Array a: [1 2 3]


In [93]:
# Create an array with evenly spaced values
b = np.arange(0, 10, 2)  # Values from 0 to 10 with step 2
print("Array b:", b)

Array b: [0 2 4 6 8]


In [95]:
# Create an array with linearly spaced values
c = np.linspace(0, 1, 5)  # 5 values evenly spaced between 0 and 1
print("Array c:", c)

Array c: [0.   0.25 0.5  0.75 1.  ]


In [97]:
# Create an array filled with zeros
d = np.zeros((2, 3))  # 2x3 array of zeros
print("Array d:\n", d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [99]:
# Create an identity matrix
f = np.eye(4)  # 4x4 identity matrix
print("Identity matrix f:\n", f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [101]:
# Reshape an array
a1 = np.array([1, 2, 3])
reshaped = np.reshape(a1, (1, 3))  # Reshape to 1x3
print("Reshaped array:", reshaped)

Reshaped array: [[1 2 3]]


In [103]:
# Flatten an array
f1 = np.array([[1, 2], [3, 4]])
flattened = np.ravel(f1)  # Flatten to 1D array
print("Flattened array:", flattened)

Flattened array: [1 2 3 4]


In [105]:
# Transpose an array
e1 = np.array([[1, 2], [3, 4]])
transposed = np.transpose(e1)  # Transpose the array
print("Transposed array:\n", transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [107]:
# Stack arrays vertically
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.vstack([a2, b2])  # Stack a and b vertically
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


In [109]:
# Add two arrays
g = np.array([1, 2, 3, 4])
added = np.add(g, 2)  # Add 2 to each element
print("Added 2 to g:", added)

Added 2 to g: [3 4 5 6]


In [111]:
# Square each element
squared = np.power(g, 2)  # Square each element
print("Squared g:", squared)

Squared g: [ 1  4  9 16]


In [113]:
# Square root of each element
sqrt_val = np.sqrt(g)  # Square root of each element
print("Square root of g:", sqrt_val)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [115]:
a3 = np.array([1, 2, 3])
dot_product = np.dot(a1, a)  # Dot product of a and g
print("Dot product of a1 and a:", dot_product)

Dot product of a1 and a: 14


In [117]:
s = np.array([1, 2, 3, 4])
mean = np.mean(s)
print("Mean of s:", mean)

Mean of s: 2.5


In [119]:
# Standard deviation of an array
std_dev = np.std(s)
print("Standard deviation of s:", std_dev)

Standard deviation of s: 1.118033988749895


In [131]:
# Minimum element of an array
minimum = np.min(s)
print("Min of s:", minimum)

Min of s: 1


In [123]:
# Maximum element of an array
maximum = np.max(s)
print("Max of s:", maximum)

Max of s: 4


In [125]:
# Create a matrix
matrix = np.array([[1, 2], [3, 4]])

In [127]:
# Determinant of a matrix
determinant = np.linalg.det(matrix)
print("Determinant of matrix:", determinant)

Determinant of matrix: -2.0000000000000004


In [129]:
# Inverse of a matrix
inverse = np.linalg.inv(matrix)
print("Inverse of matrix:\n", inverse)

Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [133]:
# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.31071904 0.6310814  0.13201528]


In [ ]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

In [135]:
# Check if all elements are True
# all
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [137]:
# Check if all elements are True
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [139]:
# Check if all elements are True
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [141]:
# Check if any elements are True
# any
any_true = np.any(logical_test)  # Check if any are True
print("Any elements True:", any_true)

Any elements True: False
